### ISSUE TITLE
How to set a name to the input

### ISSUE THREAD

**Issue by jonalxh** [Keiwen/vue-integer-plusminus#3]
Hi, this component is precisely what I need, but I'm trying to use it in a form and I need to be able to set a name to take the value when the form is submitted.

Additionally I want to style it as a bootstrap input group. The correct way is changing the slots style or what do you recommend?

**Comment by Keiwen** [comment]
Hi,
Sounds so obvious to have an input tag that I wonder why I didn't add it directly! I just publish v1.4, including a hidden input with integer in value attribute. You can use prop 'formName' to change the name attribute.

About the bootstrap input group, I do not really see what you're aiming at. Any sample/mockup?

Thanks for feedback ;)

**Comment by jonalxh** [comment]
Hi,
Can you give me an example of adding the formName?
The bootstrap input group is just an example, what I really want is to know how to add classes or styles to the buttons and the input when I add the component in my template. Could you give me an example?

**Comment by Keiwen** [comment]
You should have some info in the readme

Form name is managed as an attribute of vue tag (could be static or dynamic)
`<integer-plusminus :form-name="'myGreatName'"></integer-plusminus>`

About style, you can check the gallery I made in the demo file (docs/views/Main.vue, mainly on demo-vertical class). Example to change background for + button:
`.int-pm-increment { background: #5cb85c !important; }`
Both buttons also have 'int-pm-btn' class, value div have 'int-pm-value' class. You can examine in resulting html code all elements and classes through navigator devtools.
'!important' keyword must be used, but I never went further than this regarding style

**Comment by jonalxh** [comment]
Thanks a lot. It worked.
